### PR TITLE
SRE-97: update the order of admission controllers

### PR DESCRIPTION
**Pull request by olga-mir**
Change the order of admission controllers in order to make istio work

more details in this closed PR: https://github.com/iflix/k8s/pull/618

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Is this something that should be templated rather than hardcoded?

**Comment by olga-mir** [comment]
@SomeoneWeird as far as I understand this *is* the template from which cluster.yml is generated.

**Comment by olga-mir** [comment]
@SomeoneWeird this is in original `kube-aws` under `template` path: https://github.com/iflix/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L3189

**Review by msessa — APPROVED** [review]

**Comment by SomeoneWeird** [comment]
@olga-mir Ah, yeah, I meant like a template parameter, so you can configure it per-cluster and so it's not "hardcoded" in our template.

**Pull request merged**
